plugins: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/cache_schema.rb'
    - 'db/schema.rb'
    - 'script/**/*'

# I don't like empty lines in methods.
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Always indent 2 spaces, no exceptions.
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

# Sometimes longer methods are more readable
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10

# get and set prefixes help avoid naming collisions.
Naming/AccessorMethodName:
  Enabled: false

# Follow the Rails pattern of returning true when a method succeeds.
Naming/PredicateMethod:
  Enabled: false

# Internationalization is unnecessary.
Rails/I18nLocaleTexts:
  Enabled: false
# I promise to be careful about skipping validations.
Rails/SkipsModelValidations:
  Enabled: false

# Well-written Ruby code documents itself.
Style/Documentation:
  Enabled: false

# Boilerplate is ugly.
Style/FrozenStringLiteralComment:
  Enabled: false
