services:

  web:
    build:
      context: .
      dockerfile: production.Dockerfile
    env_file: ".env"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./storage:/rails/storage
