web:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - "80:3000"
    - "587:587"
  links:
    - db
  env_file:
    - .docker.env
    - .docker_overrides.env

db:
  image: "mysql:5.5"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: docker
