services:

  web:
    build: .
    volumes:
      - .:/rails
    ports:
      - "80:3000"
    # environment:
    #   DB_NAME: danielesplin
    #   DB_HOST: db
    #   DB_PASSWORD: docker
    #   DB_USERNAME: root
    #   FROM_EMAIL: test@example.com
