branch-defaults:
  master:
    environment: danielesplin-1
global:
  application_name: danielesplinapp
  default_ec2_keyname: daniel
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.3
    running on 64bit Amazon Linux/2.5.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
