development: &default
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  password: <%= "'#{ENV['DB_PASSWORD']}'" %>
  username: <%= ENV['DB_USERNAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
