development: &default
  adapter: postgresql
  username: postgres
  password: docker
  host: db_1
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= "'#{ENV['DB_PASSWORD']}'" %>
