DEFAULTS: &DEFAULTS
  secret_key_base: <%= "'#{ENV['SECRET_KEY_BASE'].presence || '8d669787efefbda19377777842980abd41db7777bd7789fc423e392bf3d5c387213028c1240cb9d3f3ff7fa58540b8d283ed0bdce8e063af760fe1b29cb239ee'}'" %>
  fog_bucket: <%= "'#{ENV['FOG_BUCKET']}'" %>
  fog_key: <%= "'#{ENV['FOG_KEY']}'" %>
  fog_secret: <%= "'#{ENV['FOG_SECRET']}'" %>
  emails:
    :from: <%= "'#{ENV['FROM_EMAIL']}'" %>
    :exceptions: <%= "'#{ENV['EXCEPTION_EMAIL']}'" %>
  ses_key: <%= "'#{ENV['SES_KEY']}'" %>
  ses_secret: <%= "'#{ENV['SES_SECRET']}'" %>
  embedly_key: <%= "'#{ENV['EMBEDLY_KEY']}'" %>

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
