DEFAULTS: &DEFAULTS
  fog_bucket: <%= "'#{ENV['FOG_BUCKET']}'" %>
  fog_key: <%= "'#{ENV['FOG_KEY']}'" %>
  fog_secret: <%= "'#{ENV['FOG_SECRET']}'" %>
  email_username: <%= "'#{ENV['EMAIL_USERNAME']}'" %>
  email_password: <%= "'#{ENV['EMAIL_PASSWORD']}'" %>
  secret_key_base: <%= "'#{ENV['SECRET_KEY_BASE']}'" %>

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
